[debug] [2023-11-15T11:25:30.553Z] ----------------------------------------------------------------------
[debug] [2023-11-15T11:25:30.559Z] Command:       /usr/local/bin/node /usr/local/bin/firebase init
[debug] [2023-11-15T11:25:30.559Z] CLI Version:   12.5.4
[debug] [2023-11-15T11:25:30.560Z] Platform:      darwin
[debug] [2023-11-15T11:25:30.560Z] Node Version:  v20.5.0
[debug] [2023-11-15T11:25:30.560Z] Time:          Wed Nov 15 2023 14:25:30 GMT+0300 (Москва, стандартное время)
[debug] [2023-11-15T11:25:30.560Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-11-15T11:25:30.563Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-11-15T11:25:30.691Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-11-15T11:25:30.691Z] > authorizing via signed-in user (sacraltrack@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/aleksandlr/Desktop/sacraltrack-1.4-st1.4update1.1

Before we get started, keep in mind:

  * You are initializing within an existing Firebase project directory

[debug] [2023-11-15T11:25:31.091Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-11-15T11:25:31.091Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-11-15T12:54:08.244Z] Error: read EIO
    at TTY.onStreamRead (node:internal/stream_base_commons:217:20)
